### ISSUE TITLE
Cannot find module 'main/bean/game/task-bean' or its corresponding type declarations

### ISSUE THREAD

**Issue by pwyq** [ProtectorMoe/common-protector-moe#9]
No `task-bean.ts` file under the `main/bean/game/task-bean`.

**Comment by pwyq** [comment]
By the way, @simonkimi, are you still planning to complete the project?

**Comment by simonkimi** [comment]
Nop，i'm try using flutter to rebuild this project.

**Comment by pwyq** [comment]
> Nop，i'm try using flutter to rebuild this project.

Cool, that sounds interesting. Let me know what I can help with
